const students = [
  {
    "\"StudentID": "\"56063",
    "Surname": "Alvarez",
    "GivenName": "Kristian Josef",
    "MiddleInitial": "M.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "22",
    "Q4": "13",
    "Q5": "16",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "25.25",
    "Exempted": "No",
    "TargetFinal\"": "84.5\""
  },
  {
    "\"StudentID": "\"56524",
    "Surname": "Azucena",
    "GivenName": "Rhena Joyce",
    "MiddleInitial": "F.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "41",
    "Q4": "29",
    "Q5": "22",
    "Q6": "34",
    "PreFinals": "13",
    "Tentative Grade": "34.75",
    "Exempted": "No",
    "TargetFinal\"": "65.5\""
  },
  {
    "\"StudentID": "\"54509",
    "Surname": "Bacalangco ",
    "GivenName": "Jewel Marie ",
    "MiddleInitial": "Y.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "61",
    "Q4": "12",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "18",
    "Tentative Grade": "33.75",
    "Exempted": "No",
    "TargetFinal\"": "67.5\""
  },
  {
    "\"StudentID": "\"54816",
    "Surname": "Belgira",
    "GivenName": "Mars Janel Angelo",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "42",
    "Q4": "12",
    "Q5": "22",
    "Q6": "34",
    "PreFinals": "25",
    "Tentative Grade": "33.75",
    "Exempted": "No",
    "TargetFinal\"": "67.5\""
  },
  {
    "\"StudentID": "\"55025",
    "Surname": "Bersamera",
    "GivenName": "Jeanefer",
    "MiddleInitial": "P.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "42",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "28",
    "Tentative Grade": "33.75",
    "Exempted": "No",
    "TargetFinal\"": "67.5\""
  },
  {
    "\"StudentID": "\"54752",
    "Surname": "Cabilogan",
    "GivenName": "Keyla Mae",
    "MiddleInitial": "P.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "45",
    "Q4": "19",
    "Q5": "28",
    "Q6": "34",
    "PreFinals": "32",
    "Tentative Grade": "39.5",
    "Exempted": "No",
    "TargetFinal\"": "56\""
  },
  {
    "\"StudentID": "\"56425",
    "Surname": "Cañonaso",
    "GivenName": "Elah",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "42",
    "Q4": "0",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "10",
    "Tentative Grade": "23.5",
    "Exempted": "No",
    "TargetFinal\"": "88\""
  },
  {
    "\"StudentID": "\"54550",
    "Surname": "CARTOJANO ",
    "GivenName": "SALVE",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "62",
    "Q4": "5",
    "Q5": "15",
    "Q6": "34",
    "PreFinals": "19",
    "Tentative Grade": "33.75",
    "Exempted": "No",
    "TargetFinal\"": "67.5\""
  },
  {
    "\"StudentID": "\"54384",
    "Surname": "Castaño ",
    "GivenName": "John Carlo ",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "33",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "28",
    "Exempted": "No",
    "TargetFinal\"": "79\""
  },
  {
    "\"StudentID": "\"55626",
    "Surname": "Clavines",
    "GivenName": "Rochelle",
    "MiddleInitial": "G.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "56",
    "Q4": "23",
    "Q5": "33",
    "Q6": "34",
    "PreFinals": "17",
    "Tentative Grade": "40.75",
    "Exempted": "No",
    "TargetFinal\"": "53.5\""
  },
  {
    "\"StudentID": "\"47189",
    "Surname": "Dauz III",
    "GivenName": "Antonio",
    "MiddleInitial": "B.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "30",
    "Q4": "27",
    "Q5": "22",
    "Q6": "34",
    "PreFinals": "20",
    "Tentative Grade": "33.25",
    "Exempted": "No",
    "TargetFinal\"": "68.5\""
  },
  {
    "\"StudentID": "\"55994",
    "Surname": "Gabe",
    "GivenName": "Chyzelle Jehn ",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "54",
    "Q4": "25",
    "Q5": "27",
    "Q6": "34",
    "PreFinals": "22",
    "Tentative Grade": "40.5",
    "Exempted": "No",
    "TargetFinal\"": "54\""
  },
  {
    "\"StudentID": "\"56786",
    "Surname": "Galido Jr.",
    "GivenName": "Rafael",
    "MiddleInitial": "S.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "28",
    "Q4": "13",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "28.5",
    "Exempted": "No",
    "TargetFinal\"": "78\""
  },
  {
    "\"StudentID": "\"46386",
    "Surname": "Gloria",
    "GivenName": "June Mark Anthony ",
    "MiddleInitial": "G.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "33",
    "Q4": "13",
    "Q5": "16",
    "Q6": "34",
    "PreFinals": "13",
    "Tentative Grade": "27.25",
    "Exempted": "No",
    "TargetFinal\"": "80.5\""
  },
  {
    "\"StudentID": "\"46456",
    "Surname": "Hablero",
    "GivenName": "Yancy",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "63",
    "Q4": "29",
    "Q5": "22",
    "Q6": "34",
    "PreFinals": "41",
    "Tentative Grade": "47.25",
    "Exempted": "No",
    "TargetFinal\"": "40.5\""
  },
  {
    "\"StudentID": "\"54314",
    "Surname": "Hallegado",
    "GivenName": "Jane Mariel",
    "MiddleInitial": "P.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "48",
    "Q4": "25",
    "Q5": "27",
    "Q6": "34",
    "PreFinals": "",
    "Tentative Grade": "33.5",
    "Exempted": "No",
    "TargetFinal\"": "68\""
  },
  {
    "\"StudentID": "\"54625",
    "Surname": "Herva",
    "GivenName": "Stephanie Claire ",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "44",
    "Q4": "27",
    "Q5": "22",
    "Q6": "34",
    "PreFinals": "38",
    "Tentative Grade": "41.25",
    "Exempted": "No",
    "TargetFinal\"": "52.5\""
  },
  {
    "\"StudentID": "\"56484",
    "Surname": "Jordan",
    "GivenName": "Francine Denise",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "59",
    "Q4": "0",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "38",
    "Tentative Grade": "34.75",
    "Exempted": "No",
    "TargetFinal\"": "65.5\""
  },
  {
    "\"StudentID": "\"54354",
    "Surname": "Legaspi",
    "GivenName": "Kristine Joyce",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "38",
    "Q4": "19",
    "Q5": "28",
    "Q6": "34",
    "PreFinals": "29",
    "Tentative Grade": "37",
    "Exempted": "No",
    "TargetFinal\"": "61\""
  },
  {
    "\"StudentID": "\"55437",
    "Surname": "Marterio",
    "GivenName": "Ronalyn",
    "MiddleInitial": "S.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "43",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "15",
    "Tentative Grade": "30.75",
    "Exempted": "No",
    "TargetFinal\"": "73.5\""
  },
  {
    "\"StudentID": "\"54660",
    "Surname": "Monton",
    "GivenName": "Jashiel",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "40",
    "Q4": "5",
    "Q5": "15",
    "Q6": "34",
    "PreFinals": "17",
    "Tentative Grade": "27.75",
    "Exempted": "No",
    "TargetFinal\"": "79.5\""
  },
  {
    "\"StudentID": "\"56791",
    "Surname": "Octavio",
    "GivenName": "Christian Lee",
    "MiddleInitial": "M.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "33",
    "Q4": "23",
    "Q5": "33",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "34.25",
    "Exempted": "No",
    "TargetFinal\"": "66.5\""
  },
  {
    "\"StudentID": "\"47758",
    "Surname": "Olaira",
    "GivenName": "Romualdo II",
    "MiddleInitial": "O.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "31",
    "Q4": "12",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "18",
    "Tentative Grade": "26.25",
    "Exempted": "No",
    "TargetFinal\"": "82.5\""
  },
  {
    "\"StudentID": "\"50086",
    "Surname": "Ortiz",
    "GivenName": "John Alphe",
    "MiddleInitial": "D.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "28",
    "Q4": "12",
    "Q5": "22",
    "Q6": "34",
    "PreFinals": "18",
    "Tentative Grade": "28.5",
    "Exempted": "No",
    "TargetFinal\"": "78\""
  },
  {
    "\"StudentID": "\"56746",
    "Surname": "Pacli-an",
    "GivenName": "Pink Ployd",
    "MiddleInitial": "P.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "56",
    "Q4": "13",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "18",
    "Tentative Grade": "36",
    "Exempted": "No",
    "TargetFinal\"": "63\""
  },
  {
    "\"StudentID": "\"52581",
    "Surname": "Paclibar",
    "GivenName": "Jerald Paul",
    "MiddleInitial": "P.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "65",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "18",
    "Tentative Grade": "37",
    "Exempted": "No",
    "TargetFinal\"": "61\""
  },
  {
    "\"StudentID": "\"55766",
    "Surname": "Panes",
    "GivenName": "Renet Jane ",
    "MiddleInitial": "M.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "51",
    "Q4": "13",
    "Q5": "16",
    "Q6": "34",
    "PreFinals": "34",
    "Tentative Grade": "37",
    "Exempted": "No",
    "TargetFinal\"": "61\""
  },
  {
    "\"StudentID": "\"55379",
    "Surname": "Panganiban ",
    "GivenName": "Light Markuz",
    "MiddleInitial": "T.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "34",
    "Q4": "29",
    "Q5": "22",
    "Q6": "34",
    "PreFinals": "21",
    "Tentative Grade": "35",
    "Exempted": "No",
    "TargetFinal\"": "65\""
  },
  {
    "\"StudentID": "\"52863",
    "Surname": "Sabedra",
    "GivenName": "Pamela Faith",
    "MiddleInitial": "M.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "27",
    "Q4": "12",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "21",
    "Tentative Grade": "26",
    "Exempted": "No",
    "TargetFinal\"": "83\""
  },
  {
    "\"StudentID": "\"56457",
    "Surname": "San Jose ",
    "GivenName": "John Edren ",
    "MiddleInitial": "N.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "44",
    "Q4": "0",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "21",
    "Tentative Grade": "26.75",
    "Exempted": "No",
    "TargetFinal\"": "81.5\""
  },
  {
    "\"StudentID": "\"54196",
    "Surname": "Selarde",
    "GivenName": "Kristine Joy",
    "MiddleInitial": "M.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "56",
    "Q4": "23",
    "Q5": "33",
    "Q6": "34",
    "PreFinals": "39",
    "Tentative Grade": "46.25",
    "Exempted": "No",
    "TargetFinal\"": "42.5\""
  },
  {
    "\"StudentID": "\"55902",
    "Surname": "Sumagaysay",
    "GivenName": "Marian",
    "MiddleInitial": "M.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "27",
    "Q4": "5",
    "Q5": "15",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "24.25",
    "Exempted": "No",
    "TargetFinal\"": "86.5\""
  },
  {
    "\"StudentID": "\"54677",
    "Surname": "TA-ALA",
    "GivenName": "ED MITCHEL",
    "MiddleInitial": "T.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "46",
    "Q4": "27",
    "Q5": "22",
    "Q6": "34",
    "PreFinals": "22",
    "Tentative Grade": "37.75",
    "Exempted": "No",
    "TargetFinal\"": "59.5\""
  },
  {
    "\"StudentID": "\"54837",
    "Surname": "Tante",
    "GivenName": "Jan Vincent ",
    "MiddleInitial": "N.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "50",
    "Q4": "25",
    "Q5": "27",
    "Q6": "34",
    "PreFinals": "20",
    "Tentative Grade": "39",
    "Exempted": "No",
    "TargetFinal\"": "57\""
  },
  {
    "\"StudentID": "\"55324",
    "Surname": "Tuante",
    "GivenName": "Rose Mar",
    "MiddleInitial": "T.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "47",
    "Q4": "13",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "24",
    "Tentative Grade": "35.25",
    "Exempted": "No",
    "TargetFinal\"": "64.5\""
  },
  {
    "\"StudentID": "\"55106",
    "Surname": "Tuayang ",
    "GivenName": "Adrianne Kyle ",
    "MiddleInitial": "S.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "38",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "18",
    "Tentative Grade": "30.25",
    "Exempted": "No",
    "TargetFinal\"": "74.5\""
  },
  {
    "\"StudentID": "\"49886",
    "Surname": "Villareal",
    "GivenName": "Ella Mae",
    "MiddleInitial": "D.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "43",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "21",
    "Tentative Grade": "32.25",
    "Exempted": "No",
    "TargetFinal\"": "70.5\""
  },
  {
    "\"StudentID": "\"56715",
    "Surname": "Wong",
    "GivenName": "Mar Angelo",
    "MiddleInitial": "E.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "42",
    "Q4": "19",
    "Q5": "28",
    "Q6": "34",
    "PreFinals": "20",
    "Tentative Grade": "35.75",
    "Exempted": "No",
    "TargetFinal\"": "63.5\""
  },
  {
    "\"StudentID": "\"54712",
    "Surname": "ACOLENTAVA ",
    "GivenName": "LEOMIL",
    "MiddleInitial": "M.",
    "Q1": "",
    "Q2": "15",
    "Q3": "",
    "Midterm": "37",
    "Q4": "17",
    "Q5": "18",
    "Q6": "34",
    "PreFinals": "19",
    "Tentative Grade": "35",
    "Exempted": "No",
    "TargetFinal\"": "65\""
  },
  {
    "\"StudentID": "\"47816",
    "Surname": "Agno",
    "GivenName": "Rafaela May",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "8",
    "Q3": "",
    "Midterm": "50",
    "Q4": "10",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "36",
    "Tentative Grade": "40.25",
    "Exempted": "No",
    "TargetFinal\"": "54.5\""
  },
  {
    "\"StudentID": "\"54388",
    "Surname": "Agtas",
    "GivenName": "Danz Lander",
    "MiddleInitial": "I.",
    "Q1": "",
    "Q2": "19",
    "Q3": "",
    "Midterm": "44",
    "Q4": "11",
    "Q5": "12",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "33.5",
    "Exempted": "No",
    "TargetFinal\"": "68\""
  },
  {
    "\"StudentID": "\"54490",
    "Surname": "Alfaro",
    "GivenName": "Carl Joseph",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "24",
    "Q3": "",
    "Midterm": "71",
    "Q4": "16",
    "Q5": "12",
    "Q6": "34",
    "PreFinals": "33",
    "Tentative Grade": "47.5",
    "Exempted": "No",
    "TargetFinal\"": "40\""
  },
  {
    "\"StudentID": "\"54648",
    "Surname": "Aliperio",
    "GivenName": "Carl Louis",
    "MiddleInitial": "B.",
    "Q1": "",
    "Q2": "30",
    "Q3": "",
    "Midterm": "46",
    "Q4": "17",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "33",
    "Tentative Grade": "42",
    "Exempted": "No",
    "TargetFinal\"": "51\""
  },
  {
    "\"StudentID": "\"54403",
    "Surname": "AMONTANO ",
    "GivenName": "SELWYN ADRIAN ",
    "MiddleInitial": " .",
    "Q1": "",
    "Q2": "23",
    "Q3": "",
    "Midterm": "67",
    "Q4": "17",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "30",
    "Tentative Grade": "45.25",
    "Exempted": "No",
    "TargetFinal\"": "44.5\""
  },
  {
    "\"StudentID": "\"56755",
    "Surname": "Andion ",
    "GivenName": "Wilson John ",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "24",
    "Q3": "",
    "Midterm": "54",
    "Q4": "16",
    "Q5": "14",
    "Q6": "34",
    "PreFinals": "20",
    "Tentative Grade": "40.5",
    "Exempted": "No",
    "TargetFinal\"": "54\""
  },
  {
    "\"StudentID": "\"54460",
    "Surname": "Bernaldez",
    "GivenName": "John Anthony",
    "MiddleInitial": "L.",
    "Q1": "",
    "Q2": "21",
    "Q3": "",
    "Midterm": "46",
    "Q4": "28",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "25",
    "Tentative Grade": "44.25",
    "Exempted": "No",
    "TargetFinal\"": "46.5\""
  },
  {
    "\"StudentID": "\"55952",
    "Surname": "Bernales",
    "GivenName": "Gino",
    "MiddleInitial": "E.",
    "Q1": "",
    "Q2": "16",
    "Q3": "",
    "Midterm": "44",
    "Q4": "17",
    "Q5": "28",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "38.25",
    "Exempted": "No",
    "TargetFinal\"": "58.5\""
  },
  {
    "\"StudentID": "\"56512",
    "Surname": "Bidaure ",
    "GivenName": "Keyla Jean",
    "MiddleInitial": "I.",
    "Q1": "",
    "Q2": "33",
    "Q3": "",
    "Midterm": "46",
    "Q4": "13",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "21",
    "Tentative Grade": "38.75",
    "Exempted": "No",
    "TargetFinal\"": "57.5\""
  },
  {
    "\"StudentID": "\"54431",
    "Surname": "Bigcas",
    "GivenName": "Kent Ricard",
    "MiddleInitial": "G.",
    "Q1": "",
    "Q2": "29",
    "Q3": "",
    "Midterm": "65",
    "Q4": "10",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "20",
    "Tentative Grade": "41.5",
    "Exempted": "No",
    "TargetFinal\"": "52\""
  },
  {
    "\"StudentID": "\"54469",
    "Surname": "Blegario ",
    "GivenName": "Shara Marie ",
    "MiddleInitial": "L.",
    "Q1": "",
    "Q2": "22",
    "Q3": "",
    "Midterm": "54",
    "Q4": "28",
    "Q5": "20",
    "Q6": "34",
    "PreFinals": "26",
    "Tentative Grade": "46",
    "Exempted": "No",
    "TargetFinal\"": "43\""
  },
  {
    "\"StudentID": "\"54766",
    "Surname": "Caballero",
    "GivenName": "Kenny ",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "25",
    "Q3": "",
    "Midterm": "48",
    "Q4": "19",
    "Q5": "16",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "39.5",
    "Exempted": "No",
    "TargetFinal\"": "56\""
  },
  {
    "\"StudentID": "\"57083",
    "Surname": "Calzado ",
    "GivenName": "Charles Mark ",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "25",
    "Q3": "",
    "Midterm": "60",
    "Q4": "17",
    "Q5": "18",
    "Q6": "34",
    "PreFinals": "37",
    "Tentative Grade": "47.75",
    "Exempted": "No",
    "TargetFinal\"": "39.5\""
  },
  {
    "\"StudentID": "\"51114",
    "Surname": "Candelario",
    "GivenName": "Miles",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "32",
    "Q4": "16",
    "Q5": "28",
    "Q6": "",
    "PreFinals": "16",
    "Tentative Grade": "23",
    "Exempted": "No",
    "TargetFinal\"": "89\""
  },
  {
    "\"StudentID": "\"54607",
    "Surname": "Capito",
    "GivenName": "Divine Mae",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "27",
    "Q3": "",
    "Midterm": "54",
    "Q4": "28",
    "Q5": "20",
    "Q6": "34",
    "PreFinals": "25",
    "Tentative Grade": "47",
    "Exempted": "No",
    "TargetFinal\"": "41\""
  },
  {
    "\"StudentID": "\"55510",
    "Surname": "Caspillo",
    "GivenName": "Xyrene Frenz",
    "MiddleInitial": "J.",
    "Q1": "",
    "Q2": "27",
    "Q3": "",
    "Midterm": "37",
    "Q4": "16",
    "Q5": "12",
    "Q6": "34",
    "PreFinals": "29",
    "Tentative Grade": "38.75",
    "Exempted": "No",
    "TargetFinal\"": "57.5\""
  },
  {
    "\"StudentID": "\"34781",
    "Surname": "Castulo",
    "GivenName": "Jaymark",
    "MiddleInitial": "R.",
    "Q1": "",
    "Q2": "32",
    "Q3": "",
    "Midterm": "63",
    "Q4": "10",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "26",
    "Tentative Grade": "43.25",
    "Exempted": "No",
    "TargetFinal\"": "48.5\""
  },
  {
    "\"StudentID": "\"55439",
    "Surname": "Cuarte",
    "GivenName": "Maxxine",
    "MiddleInitial": "N.",
    "Q1": "",
    "Q2": "8",
    "Q3": "",
    "Midterm": "38",
    "Q4": "13",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "24",
    "Tentative Grade": "31.25",
    "Exempted": "No",
    "TargetFinal\"": "72.5\""
  },
  {
    "\"StudentID": "\"56363",
    "Surname": "Derla",
    "GivenName": "John Gregor",
    "MiddleInitial": "G.",
    "Q1": "",
    "Q2": "23",
    "Q3": "",
    "Midterm": "62",
    "Q4": "17",
    "Q5": "28",
    "Q6": "34",
    "PreFinals": "34",
    "Tentative Grade": "49.5",
    "Exempted": "No",
    "TargetFinal\"": "36\""
  },
  {
    "\"StudentID": "\"52538",
    "Surname": "Equinan",
    "GivenName": "Rhona May",
    "MiddleInitial": "S.",
    "Q1": "",
    "Q2": "5",
    "Q3": "",
    "Midterm": "28",
    "Q4": "17",
    "Q5": "10",
    "Q6": "",
    "PreFinals": "18",
    "Tentative Grade": "19.5",
    "Exempted": "No",
    "TargetFinal\"": "96\""
  },
  {
    "\"StudentID": "\"56812",
    "Surname": "Ezpeleta",
    "GivenName": "Jerelyn",
    "MiddleInitial": "E.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "55",
    "Q4": "19",
    "Q5": "16",
    "Q6": "34",
    "PreFinals": "32",
    "Tentative Grade": "39",
    "Exempted": "No",
    "TargetFinal\"": "57\""
  },
  {
    "\"StudentID": "\"54400",
    "Surname": "Fuene",
    "GivenName": "Anthony",
    "MiddleInitial": "G.",
    "Q1": "",
    "Q2": "27",
    "Q3": "",
    "Midterm": "67",
    "Q4": "28",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "30",
    "Tentative Grade": "52.25",
    "Exempted": "No",
    "TargetFinal\"": "30.5\""
  },
  {
    "\"StudentID": "\"57244",
    "Surname": "Galvan ",
    "GivenName": "Kyrah Riz ",
    "MiddleInitial": "M.",
    "Q1": "",
    "Q2": "3",
    "Q3": "",
    "Midterm": "33",
    "Q4": "17",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "22",
    "Tentative Grade": "29.25",
    "Exempted": "No",
    "TargetFinal\"": "76.5\""
  },
  {
    "\"StudentID": "\"46454",
    "Surname": "Golviogo",
    "GivenName": "Julliene Marie",
    "MiddleInitial": "B.",
    "Q1": "",
    "Q2": "23",
    "Q3": "",
    "Midterm": "41",
    "Q4": "10",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "35",
    "Tentative Grade": "41.5",
    "Exempted": "No",
    "TargetFinal\"": "52\""
  },
  {
    "\"StudentID": "\"55751",
    "Surname": "LABRADOR",
    "GivenName": "MITZI",
    "MiddleInitial": "P.",
    "Q1": "",
    "Q2": "7",
    "Q3": "",
    "Midterm": "46",
    "Q4": "16",
    "Q5": "14",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "33.25",
    "Exempted": "No",
    "TargetFinal\"": "68.5\""
  },
  {
    "\"StudentID": "\"55454",
    "Surname": "Lacuesta",
    "GivenName": "Kholenne",
    "MiddleInitial": "D.",
    "Q1": "",
    "Q2": "20",
    "Q3": "",
    "Midterm": "50",
    "Q4": "11",
    "Q5": "12",
    "Q6": "34",
    "PreFinals": "34",
    "Tentative Grade": "40.25",
    "Exempted": "No",
    "TargetFinal\"": "54.5\""
  },
  {
    "\"StudentID": "\"46317",
    "Surname": "Lo",
    "GivenName": "Elisha Glaze",
    "MiddleInitial": "S.",
    "Q1": "",
    "Q2": "7",
    "Q3": "",
    "Midterm": "65",
    "Q4": "17",
    "Q5": "18",
    "Q6": "34",
    "PreFinals": "35",
    "Tentative Grade": "44",
    "Exempted": "No",
    "TargetFinal\"": "47\""
  },
  {
    "\"StudentID": "\"52293",
    "Surname": "Lozada",
    "GivenName": "Miamie",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "17",
    "Q3": "",
    "Midterm": "44",
    "Q4": "16",
    "Q5": "28",
    "Q6": "34",
    "PreFinals": "12",
    "Tentative Grade": "37.75",
    "Exempted": "No",
    "TargetFinal\"": "59.5\""
  },
  {
    "\"StudentID": "\"55383",
    "Surname": "Macahilig ",
    "GivenName": "Joshua",
    "MiddleInitial": "P.",
    "Q1": "",
    "Q2": "16",
    "Q3": "",
    "Midterm": "39",
    "Q4": "17",
    "Q5": "28",
    "Q6": "34",
    "PreFinals": "26",
    "Tentative Grade": "40",
    "Exempted": "No",
    "TargetFinal\"": "55\""
  },
  {
    "\"StudentID": "\"54548",
    "Surname": "Marquez",
    "GivenName": "MZ Joy",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "6",
    "Q3": "",
    "Midterm": "46",
    "Q4": "12",
    "Q5": "22",
    "Q6": "34",
    "PreFinals": "12",
    "Tentative Grade": "33",
    "Exempted": "No",
    "TargetFinal\"": "69\""
  },
  {
    "\"StudentID": "\"47402",
    "Surname": "Mendiola",
    "GivenName": "Ken David",
    "MiddleInitial": "H.",
    "Q1": "",
    "Q2": "17",
    "Q3": "",
    "Midterm": "66",
    "Q4": "19",
    "Q5": "16",
    "Q6": "34",
    "PreFinals": "24",
    "Tentative Grade": "44",
    "Exempted": "No",
    "TargetFinal\"": "47\""
  },
  {
    "\"StudentID": "\"54653",
    "Surname": "Miranda",
    "GivenName": "Mark John",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "13",
    "Q3": "",
    "Midterm": "52",
    "Q4": "28",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "29",
    "Tentative Grade": "44.75",
    "Exempted": "No",
    "TargetFinal\"": "45.5\""
  },
  {
    "\"StudentID": "\"55273",
    "Surname": "Navarro ",
    "GivenName": "Joshua",
    "MiddleInitial": "B.",
    "Q1": "",
    "Q2": "5",
    "Q3": "",
    "Midterm": "52",
    "Q4": "11",
    "Q5": "12",
    "Q6": "34",
    "PreFinals": "22",
    "Tentative Grade": "34",
    "Exempted": "No",
    "TargetFinal\"": "67\""
  },
  {
    "\"StudentID": "\"42138",
    "Surname": "Patano",
    "GivenName": "Lady Marie",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "",
    "Q3": "",
    "Midterm": "",
    "Q4": "0",
    "Q5": "0",
    "Q6": "",
    "PreFinals": "8",
    "Tentative Grade": "2",
    "Exempted": "No",
    "TargetFinal\"": "131\""
  },
  {
    "\"StudentID": "\"55411",
    "Surname": "Quijano",
    "GivenName": "Alexander",
    "MiddleInitial": "T.",
    "Q1": "",
    "Q2": "11",
    "Q3": "",
    "Midterm": "47",
    "Q4": "10",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "27",
    "Tentative Grade": "38",
    "Exempted": "No",
    "TargetFinal\"": "59\""
  },
  {
    "\"StudentID": "\"54337",
    "Surname": "Solvero",
    "GivenName": "Starlyn",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "20",
    "Q3": "",
    "Midterm": "72",
    "Q4": "17",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "30",
    "Tentative Grade": "45.25",
    "Exempted": "No",
    "TargetFinal\"": "44.5\""
  },
  {
    "\"StudentID": "\"55408",
    "Surname": "Soroño",
    "GivenName": "Carmelyn",
    "MiddleInitial": "B.",
    "Q1": "",
    "Q2": "5",
    "Q3": "",
    "Midterm": "43",
    "Q4": "10",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "26",
    "Tentative Grade": "31.5",
    "Exempted": "No",
    "TargetFinal\"": "72\""
  },
  {
    "\"StudentID": "\"54422",
    "Surname": "Suyat",
    "GivenName": "Loise Antonitte ",
    "MiddleInitial": "D.",
    "Q1": "",
    "Q2": "16",
    "Q3": "",
    "Midterm": "41",
    "Q4": "16",
    "Q5": "14",
    "Q6": "34",
    "PreFinals": "26",
    "Tentative Grade": "36.75",
    "Exempted": "No",
    "TargetFinal\"": "61.5\""
  },
  {
    "\"StudentID": "\"54680",
    "Surname": "Tabujara ",
    "GivenName": "Daisyrick Novem ",
    "MiddleInitial": "V.",
    "Q1": "",
    "Q2": "10",
    "Q3": "",
    "Midterm": "38",
    "Q4": "13",
    "Q5": "8",
    "Q6": "34",
    "PreFinals": "31",
    "Tentative Grade": "33.5",
    "Exempted": "No",
    "TargetFinal\"": "68\""
  },
  {
    "\"StudentID": "\"55276",
    "Surname": "Traigo",
    "GivenName": "Johanna Trixia",
    "MiddleInitial": "G.",
    "Q1": "",
    "Q2": "3",
    "Q3": "",
    "Midterm": "44",
    "Q4": "16",
    "Q5": "28",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "35.25",
    "Exempted": "No",
    "TargetFinal\"": "64.5\""
  },
  {
    "\"StudentID": "\"56444",
    "Surname": "Valencia ",
    "GivenName": "Francine Ross ",
    "MiddleInitial": "B.",
    "Q1": "",
    "Q2": "18",
    "Q3": "",
    "Midterm": "69",
    "Q4": "17",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "30",
    "Tentative Grade": "44.5",
    "Exempted": "No",
    "TargetFinal\"": "46\""
  },
  {
    "\"StudentID": "\"54566",
    "Surname": "Villanueva",
    "GivenName": "Narzvil",
    "MiddleInitial": "G.",
    "Q1": "",
    "Q2": "18",
    "Q3": "",
    "Midterm": "58",
    "Q4": "28",
    "Q5": "20",
    "Q6": "34",
    "PreFinals": "41",
    "Tentative Grade": "49.75",
    "Exempted": "No",
    "TargetFinal\"": "35.5\""
  },
  {
    "\"StudentID": "\"52978",
    "Surname": "Villaruel",
    "GivenName": "Benjie",
    "MiddleInitial": "B.",
    "Q1": "",
    "Q2": "13",
    "Q3": "",
    "Midterm": "67",
    "Q4": "16",
    "Q5": "12",
    "Q6": "43",
    "PreFinals": "29",
    "Tentative Grade": "45",
    "Exempted": "No",
    "TargetFinal\"": "45\""
  },
  {
    "\"StudentID": "\"57153",
    "Surname": "Abordo ",
    "GivenName": "Lonnie ",
    "MiddleInitial": "M.",
    "Q1": "21",
    "Q2": "22",
    "Q3": "",
    "Midterm": "63",
    "Q4": "25",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "46",
    "Tentative Grade": "60.5",
    "Exempted": "Yes",
    "TargetFinal\"": "14\""
  },
  {
    "\"StudentID": "\"54596",
    "Surname": "Agustin",
    "GivenName": "Wilriche Daisy",
    "MiddleInitial": "D.",
    "Q1": "11",
    "Q2": "25",
    "Q3": "",
    "Midterm": "58",
    "Q4": "33",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "43",
    "Tentative Grade": "58.75",
    "Exempted": "No",
    "TargetFinal\"": "17.5\""
  },
  {
    "\"StudentID": "\"54644",
    "Surname": "Almoceda",
    "GivenName": "Darryl",
    "MiddleInitial": "M.",
    "Q1": "17",
    "Q2": "18",
    "Q3": "",
    "Midterm": "69",
    "Q4": "31",
    "Q5": "2",
    "Q6": "34",
    "PreFinals": "38",
    "Tentative Grade": "52.25",
    "Exempted": "No",
    "TargetFinal\"": "30.5\""
  },
  {
    "\"StudentID": "\"55305",
    "Surname": "Amante",
    "GivenName": "Mc Jiezel",
    "MiddleInitial": "L.",
    "Q1": "22",
    "Q2": "33",
    "Q3": "",
    "Midterm": "68",
    "Q4": "29",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "23",
    "Tentative Grade": "60",
    "Exempted": "Yes",
    "TargetFinal\"": "15\""
  },
  {
    "\"StudentID": "\"53883",
    "Surname": "Anativo",
    "GivenName": "Claudine",
    "MiddleInitial": "L.",
    "Q1": "18",
    "Q2": "16",
    "Q3": "",
    "Midterm": "80",
    "Q4": "9",
    "Q5": "11",
    "Q6": "34",
    "PreFinals": "31",
    "Tentative Grade": "49.75",
    "Exempted": "No",
    "TargetFinal\"": "35.5\""
  },
  {
    "\"StudentID": "\"54637",
    "Surname": "Apitong",
    "GivenName": "Rhea",
    "MiddleInitial": "E.",
    "Q1": "26",
    "Q2": "20",
    "Q3": "",
    "Midterm": "39",
    "Q4": "29",
    "Q5": "20",
    "Q6": "34",
    "PreFinals": "33",
    "Tentative Grade": "50.25",
    "Exempted": "No",
    "TargetFinal\"": "34.5\""
  },
  {
    "\"StudentID": "\"49873",
    "Surname": "Arante",
    "GivenName": "Tania Cate",
    "MiddleInitial": "P.",
    "Q1": "",
    "Q2": "5",
    "Q3": "",
    "Midterm": "52",
    "Q4": "31",
    "Q5": "21",
    "Q6": "34",
    "PreFinals": "26",
    "Tentative Grade": "42.25",
    "Exempted": "No",
    "TargetFinal\"": "50.5\""
  },
  {
    "\"StudentID": "\"56039",
    "Surname": "Ariaden",
    "GivenName": "Zaira Marie",
    "MiddleInitial": "L.",
    "Q1": "15",
    "Q2": "24",
    "Q3": "",
    "Midterm": "58",
    "Q4": "26",
    "Q5": "18",
    "Q6": "34",
    "PreFinals": "25",
    "Tentative Grade": "50",
    "Exempted": "No",
    "TargetFinal\"": "35\""
  },
  {
    "\"StudentID": "\"56031",
    "Surname": "Bajade",
    "GivenName": "Florenio",
    "MiddleInitial": "P.",
    "Q1": "19",
    "Q2": "28",
    "Q3": "",
    "Midterm": "67",
    "Q4": "29",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "36",
    "Tentative Grade": "59",
    "Exempted": "No",
    "TargetFinal\"": "17\""
  },
  {
    "\"StudentID": "\"46549",
    "Surname": "Barretto",
    "GivenName": "Mary Rose",
    "MiddleInitial": "D.",
    "Q1": "9",
    "Q2": "28",
    "Q3": "",
    "Midterm": "46",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "19",
    "Tentative Grade": "41.75",
    "Exempted": "No",
    "TargetFinal\"": "51.5\""
  },
  {
    "\"StudentID": "\"54697",
    "Surname": "Bolivar",
    "GivenName": "Cyrene June",
    "MiddleInitial": "B.",
    "Q1": "26",
    "Q2": "29",
    "Q3": "",
    "Midterm": "72",
    "Q4": "33",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "48",
    "Tentative Grade": "68.25",
    "Exempted": "Yes",
    "TargetFinal\"": "-1.5\""
  },
  {
    "\"StudentID": "\"56172",
    "Surname": "Cantollino",
    "GivenName": "Kyla",
    "MiddleInitial": "C.",
    "Q1": "12",
    "Q2": "25",
    "Q3": "",
    "Midterm": "86",
    "Q4": "29",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "38",
    "Tentative Grade": "63.75",
    "Exempted": "Yes",
    "TargetFinal\"": "7.5\""
  },
  {
    "\"StudentID": "\"54421",
    "Surname": "Caro",
    "GivenName": "Renz",
    "MiddleInitial": "E.",
    "Q1": "18",
    "Q2": "33",
    "Q3": "",
    "Midterm": "63",
    "Q4": "33",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "38",
    "Tentative Grade": "62.5",
    "Exempted": "Yes",
    "TargetFinal\"": "10\""
  },
  {
    "\"StudentID": "\"46120",
    "Surname": "Casio",
    "GivenName": "Jules",
    "MiddleInitial": "R.",
    "Q1": "14",
    "Q2": "20",
    "Q3": "",
    "Midterm": "52",
    "Q4": "25",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "40",
    "Tentative Grade": "54",
    "Exempted": "No",
    "TargetFinal\"": "27\""
  },
  {
    "\"StudentID": "\"50250",
    "Surname": "Ceralvo",
    "GivenName": "Joshua ",
    "MiddleInitial": "A.",
    "Q1": "6",
    "Q2": "4",
    "Q3": "",
    "Midterm": "15",
    "Q4": "26",
    "Q5": "18",
    "Q6": "34",
    "PreFinals": "12",
    "Tentative Grade": "28.75",
    "Exempted": "No",
    "TargetFinal\"": "77.5\""
  },
  {
    "\"StudentID": "\"42891",
    "Surname": "Depaor",
    "GivenName": "Jade",
    "MiddleInitial": "C.",
    "Q1": "3",
    "Q2": "9",
    "Q3": "",
    "Midterm": "33",
    "Q4": "24",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "19",
    "Tentative Grade": "36.25",
    "Exempted": "No",
    "TargetFinal\"": "62.5\""
  },
  {
    "\"StudentID": "\"51513",
    "Surname": "EBRON",
    "GivenName": "AICYLL MAE",
    "MiddleInitial": "R.",
    "Q1": "17",
    "Q2": "18",
    "Q3": "",
    "Midterm": "59",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "10",
    "Tentative Grade": "42.25",
    "Exempted": "No",
    "TargetFinal\"": "50.5\""
  },
  {
    "\"StudentID": "\"55928",
    "Surname": "Espino",
    "GivenName": "Christine",
    "MiddleInitial": "S.",
    "Q1": "24",
    "Q2": "20",
    "Q3": "",
    "Midterm": "60",
    "Q4": "31",
    "Q5": "21",
    "Q6": "34",
    "PreFinals": "27",
    "Tentative Grade": "54.25",
    "Exempted": "No",
    "TargetFinal\"": "26.5\""
  },
  {
    "\"StudentID": "\"56477",
    "Surname": "Fortaleza ",
    "GivenName": "Marco Chester ",
    "MiddleInitial": "G.",
    "Q1": "13",
    "Q2": "6",
    "Q3": "",
    "Midterm": "64",
    "Q4": "29",
    "Q5": "20",
    "Q6": "34",
    "PreFinals": "32",
    "Tentative Grade": "49.5",
    "Exempted": "No",
    "TargetFinal\"": "36\""
  },
  {
    "\"StudentID": "\"41699",
    "Surname": "Gatuteo",
    "GivenName": "Mark Angelo",
    "MiddleInitial": "O.",
    "Q1": "8",
    "Q2": "0",
    "Q3": "",
    "Midterm": "34",
    "Q4": "31",
    "Q5": "2",
    "Q6": "34",
    "PreFinals": "12",
    "Tentative Grade": "30.25",
    "Exempted": "No",
    "TargetFinal\"": "74.5\""
  },
  {
    "\"StudentID": "\"56491",
    "Surname": "GAYAS",
    "GivenName": "CRYSTAL MARRIE",
    "MiddleInitial": "S.",
    "Q1": "8",
    "Q2": "19",
    "Q3": "",
    "Midterm": "28",
    "Q4": "33",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "42.25",
    "Exempted": "No",
    "TargetFinal\"": "50.5\""
  },
  {
    "\"StudentID": "\"41706",
    "Surname": "Gedalanga",
    "GivenName": "Riz Alfred",
    "MiddleInitial": "B.",
    "Q1": "6",
    "Q2": "0",
    "Q3": "",
    "Midterm": "21",
    "Q4": "9",
    "Q5": "11",
    "Q6": "34",
    "PreFinals": "10",
    "Tentative Grade": "22.75",
    "Exempted": "No",
    "TargetFinal\"": "89.5\""
  },
  {
    "\"StudentID": "\"54881",
    "Surname": "Goleña",
    "GivenName": "Theo Joshua",
    "MiddleInitial": "N.",
    "Q1": "28",
    "Q2": "27",
    "Q3": "",
    "Midterm": "64",
    "Q4": "31",
    "Q5": "21",
    "Q6": "34",
    "PreFinals": "48",
    "Tentative Grade": "63.25",
    "Exempted": "Yes",
    "TargetFinal\"": "8.50000000000001\""
  },
  {
    "\"StudentID": "\"41695",
    "Surname": "Guevara",
    "GivenName": "Blez",
    "MiddleInitial": "M.",
    "Q1": "8",
    "Q2": "3",
    "Q3": "",
    "Midterm": "35",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "31.25",
    "Exempted": "No",
    "TargetFinal\"": "72.5\""
  },
  {
    "\"StudentID": "\"56166",
    "Surname": "Jaleco",
    "GivenName": "Warren",
    "MiddleInitial": ".",
    "Q1": "17",
    "Q2": "19",
    "Q3": "",
    "Midterm": "70",
    "Q4": "26",
    "Q5": "18",
    "Q6": "34",
    "PreFinals": "41",
    "Tentative Grade": "56.25",
    "Exempted": "No",
    "TargetFinal\"": "22.5\""
  },
  {
    "\"StudentID": "\"54576",
    "Surname": "Libuna",
    "GivenName": "Sarah",
    "MiddleInitial": "B.",
    "Q1": "19",
    "Q2": "25",
    "Q3": "",
    "Midterm": "59",
    "Q4": "33",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "54.25",
    "Exempted": "No",
    "TargetFinal\"": "26.5\""
  },
  {
    "\"StudentID": "\"56564",
    "Surname": "Maghari",
    "GivenName": "Cristelear Rose Carl",
    "MiddleInitial": "L.",
    "Q1": "4",
    "Q2": "14",
    "Q3": "",
    "Midterm": "32",
    "Q4": "33",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "40.5",
    "Exempted": "No",
    "TargetFinal\"": "54\""
  },
  {
    "\"StudentID": "\"54459",
    "Surname": "Menil",
    "GivenName": "Angelbert Ian",
    "MiddleInitial": "F.",
    "Q1": "12",
    "Q2": "16",
    "Q3": "",
    "Midterm": "57",
    "Q4": "9",
    "Q5": "11",
    "Q6": "34",
    "PreFinals": "26",
    "Tentative Grade": "41.25",
    "Exempted": "No",
    "TargetFinal\"": "52.5\""
  },
  {
    "\"StudentID": "\"55297",
    "Surname": "Mirasol",
    "GivenName": "Jasper Bryan",
    "MiddleInitial": "P.",
    "Q1": "23",
    "Q2": "33",
    "Q3": "",
    "Midterm": "81",
    "Q4": "29",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "37",
    "Tentative Grade": "65",
    "Exempted": "Yes",
    "TargetFinal\"": "5.00000000000001\""
  },
  {
    "\"StudentID": "\"46320",
    "Surname": "Panaguiton",
    "GivenName": "Joan Marie",
    "MiddleInitial": "T.",
    "Q1": "6",
    "Q2": "16",
    "Q3": "",
    "Midterm": "54",
    "Q4": "25",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "45.5",
    "Exempted": "No",
    "TargetFinal\"": "44\""
  },
  {
    "\"StudentID": "\"46131",
    "Surname": "Pastolero",
    "GivenName": "Clea Frence",
    "MiddleInitial": "P.",
    "Q1": "23",
    "Q2": "33",
    "Q3": "",
    "Midterm": "66",
    "Q4": "29",
    "Q5": "20",
    "Q6": "34",
    "PreFinals": "38",
    "Tentative Grade": "60.75",
    "Exempted": "Yes",
    "TargetFinal\"": "13.5\""
  },
  {
    "\"StudentID": "\"54863",
    "Surname": "Patriarca",
    "GivenName": "Van Deomar",
    "MiddleInitial": "P.",
    "Q1": "21",
    "Q2": "27",
    "Q3": "",
    "Midterm": "75",
    "Q4": "31",
    "Q5": "2",
    "Q6": "34",
    "PreFinals": "44",
    "Tentative Grade": "58.5",
    "Exempted": "No",
    "TargetFinal\"": "18\""
  },
  {
    "\"StudentID": "\"55235",
    "Surname": "PEREZ",
    "GivenName": "CLARISSA",
    "MiddleInitial": "P.",
    "Q1": "11",
    "Q2": "15",
    "Q3": "",
    "Midterm": "42",
    "Q4": "23",
    "Q5": "29",
    "Q6": "34",
    "PreFinals": "21",
    "Tentative Grade": "43.75",
    "Exempted": "No",
    "TargetFinal\"": "47.5\""
  },
  {
    "\"StudentID": "\"56016",
    "Surname": "PORRAS",
    "GivenName": "ALEXIA PEARL",
    "MiddleInitial": "A.",
    "Q1": "",
    "Q2": "10",
    "Q3": "",
    "Midterm": "63",
    "Q4": "21",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "32",
    "Tentative Grade": "42.5",
    "Exempted": "No",
    "TargetFinal\"": "50\""
  },
  {
    "\"StudentID": "\"52383",
    "Surname": "Porras",
    "GivenName": "Paul Vincent",
    "MiddleInitial": "E.",
    "Q1": "21",
    "Q2": "",
    "Q3": "",
    "Midterm": "40",
    "Q4": "25",
    "Q5": "27",
    "Q6": "34",
    "PreFinals": "35",
    "Tentative Grade": "45.5",
    "Exempted": "No",
    "TargetFinal\"": "44\""
  },
  {
    "\"StudentID": "\"55922",
    "Surname": "Sarabia",
    "GivenName": "Antonette",
    "MiddleInitial": "D.",
    "Q1": "17",
    "Q2": "17",
    "Q3": "",
    "Midterm": "59",
    "Q4": "29",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "19",
    "Tentative Grade": "49.5",
    "Exempted": "No",
    "TargetFinal\"": "36\""
  },
  {
    "\"StudentID": "\"46830",
    "Surname": "Sayo",
    "GivenName": "Robert Eduard",
    "MiddleInitial": "B.",
    "Q1": "14",
    "Q2": "21",
    "Q3": "",
    "Midterm": "60",
    "Q4": "29",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "41",
    "Tentative Grade": "57.5",
    "Exempted": "No",
    "TargetFinal\"": "20\""
  },
  {
    "\"StudentID": "\"56771",
    "Surname": "Suelo",
    "GivenName": "Alfred",
    "MiddleInitial": "L.",
    "Q1": "23",
    "Q2": "33",
    "Q3": "",
    "Midterm": "77",
    "Q4": "33",
    "Q5": "31",
    "Q6": "34",
    "PreFinals": "34",
    "Tentative Grade": "66.25",
    "Exempted": "Yes",
    "TargetFinal\"": "2.50000000000001\""
  },
  {
    "\"StudentID": "\"55356",
    "Surname": "Vidal",
    "GivenName": "John Michael",
    "MiddleInitial": "O.",
    "Q1": "15",
    "Q2": "23",
    "Q3": "",
    "Midterm": "76",
    "Q4": "29",
    "Q5": "20",
    "Q6": "34",
    "PreFinals": "32",
    "Tentative Grade": "57.25",
    "Exempted": "No",
    "TargetFinal\"": "20.5\""
  },
  {
    "\"StudentID": "\"54857",
    "Surname": "Babayen-on",
    "GivenName": "Noven",
    "MiddleInitial": "C.",
    "Q1": "13",
    "Q2": "23",
    "Q3": "",
    "Midterm": "44",
    "Q4": "21",
    "Q5": "14",
    "Q6": "34",
    "PreFinals": "10",
    "Tentative Grade": "39.75",
    "Exempted": "No",
    "TargetFinal\"": "55.5\""
  },
  {
    "\"StudentID": "\"45669",
    "Surname": "Babunas",
    "GivenName": "Siobee",
    "MiddleInitial": "B.",
    "Q1": "10",
    "Q2": "7",
    "Q3": "",
    "Midterm": "50",
    "Q4": "21",
    "Q5": "27",
    "Q6": "34",
    "PreFinals": "25",
    "Tentative Grade": "43.5",
    "Exempted": "No",
    "TargetFinal\"": "48\""
  },
  {
    "\"StudentID": "\"56346",
    "Surname": "Bachoco ",
    "GivenName": "Lyn Iris ",
    "MiddleInitial": "B.",
    "Q1": "10",
    "Q2": "18",
    "Q3": "",
    "Midterm": "45",
    "Q4": "25",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "31",
    "Tentative Grade": "46.5",
    "Exempted": "No",
    "TargetFinal\"": "42\""
  },
  {
    "\"StudentID": "\"56115",
    "Surname": "Banate Jr.",
    "GivenName": "Ruben Vincent",
    "MiddleInitial": "G.",
    "Q1": "1",
    "Q2": "21",
    "Q3": "",
    "Midterm": "46",
    "Q4": "3",
    "Q5": "4",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "30.75",
    "Exempted": "No",
    "TargetFinal\"": "73.5\""
  },
  {
    "\"StudentID": "\"56210",
    "Surname": "Biñas",
    "GivenName": "Khen",
    "MiddleInitial": "C.",
    "Q1": "0",
    "Q2": "9",
    "Q3": "",
    "Midterm": "30",
    "Q4": "24",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "33.5",
    "Exempted": "No",
    "TargetFinal\"": "68\""
  },
  {
    "\"StudentID": "\"52465",
    "Surname": "BUGNA",
    "GivenName": "JONNA MAE",
    "MiddleInitial": "S.",
    "Q1": "6",
    "Q2": "13",
    "Q3": "",
    "Midterm": "52",
    "Q4": "17",
    "Q5": "33",
    "Q6": "34",
    "PreFinals": "22",
    "Tentative Grade": "44.25",
    "Exempted": "No",
    "TargetFinal\"": "46.5\""
  },
  {
    "\"StudentID": "\"56337",
    "Surname": "Calopez",
    "GivenName": "Joenald",
    "MiddleInitial": "G.",
    "Q1": "8",
    "Q2": "5",
    "Q3": "",
    "Midterm": "38",
    "Q4": "3",
    "Q5": "9",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "27.75",
    "Exempted": "No",
    "TargetFinal\"": "79.5\""
  },
  {
    "\"StudentID": "\"50318",
    "Surname": "COLMO",
    "GivenName": "FRANZ RUIZ",
    "MiddleInitial": "A.",
    "Q1": "4",
    "Q2": "",
    "Q3": "",
    "Midterm": "37",
    "Q4": "17",
    "Q5": "12",
    "Q6": "34",
    "PreFinals": "25",
    "Tentative Grade": "32.25",
    "Exempted": "No",
    "TargetFinal\"": "70.5\""
  },
  {
    "\"StudentID": "\"52804",
    "Surname": "Dominguez",
    "GivenName": "Lydeth Kaye",
    "MiddleInitial": "C.",
    "Q1": "6",
    "Q2": "10",
    "Q3": "",
    "Midterm": "32",
    "Q4": "23",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "10",
    "Tentative Grade": "34.5",
    "Exempted": "No",
    "TargetFinal\"": "66\""
  },
  {
    "\"StudentID": "\"49066",
    "Surname": "Duro",
    "GivenName": "Judy Jr.",
    "MiddleInitial": "C.",
    "Q1": "9",
    "Q2": "22",
    "Q3": "",
    "Midterm": "65",
    "Q4": "25",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "21",
    "Tentative Grade": "46.5",
    "Exempted": "No",
    "TargetFinal\"": "42\""
  },
  {
    "\"StudentID": "\"55174",
    "Surname": "Ellado",
    "GivenName": "Ma. Kyla Cassandra ",
    "MiddleInitial": "D.",
    "Q1": "5",
    "Q2": "32",
    "Q3": "",
    "Midterm": "26",
    "Q4": "10",
    "Q5": "2",
    "Q6": "34",
    "PreFinals": "20",
    "Tentative Grade": "32.25",
    "Exempted": "No",
    "TargetFinal\"": "70.5\""
  },
  {
    "\"StudentID": "\"55913",
    "Surname": "Endoma",
    "GivenName": "Tracy Liane",
    "MiddleInitial": "N.",
    "Q1": "4",
    "Q2": "20",
    "Q3": "",
    "Midterm": "39",
    "Q4": "",
    "Q5": "",
    "Q6": "34",
    "PreFinals": "22",
    "Tentative Grade": "29.75",
    "Exempted": "No",
    "TargetFinal\"": "75.5\""
  },
  {
    "\"StudentID": "\"55434",
    "Surname": "Estañol",
    "GivenName": "Noezel",
    "MiddleInitial": "G.",
    "Q1": "5",
    "Q2": "12",
    "Q3": "",
    "Midterm": "34",
    "Q4": "24",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "34",
    "Tentative Grade": "41.5",
    "Exempted": "No",
    "TargetFinal\"": "52\""
  },
  {
    "\"StudentID": "\"54585",
    "Surname": "Fullon",
    "GivenName": "Romar John",
    "MiddleInitial": "G.",
    "Q1": "7",
    "Q2": "31",
    "Q3": "",
    "Midterm": "60",
    "Q4": "21",
    "Q5": "14",
    "Q6": "34",
    "PreFinals": "34",
    "Tentative Grade": "50.25",
    "Exempted": "No",
    "TargetFinal\"": "34.5\""
  },
  {
    "\"StudentID": "\"38429",
    "Surname": "Gagula",
    "GivenName": "Emmanuel Jay",
    "MiddleInitial": "G.",
    "Q1": "6",
    "Q2": "17",
    "Q3": "",
    "Midterm": "41",
    "Q4": "24",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "25",
    "Tentative Grade": "42.5",
    "Exempted": "No",
    "TargetFinal\"": "50\""
  },
  {
    "\"StudentID": "\"56606",
    "Surname": "Genit",
    "GivenName": "Algene June ",
    "MiddleInitial": "M.",
    "Q1": "1",
    "Q2": "23",
    "Q3": "",
    "Midterm": "38",
    "Q4": "25",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "28",
    "Tentative Grade": "43",
    "Exempted": "No",
    "TargetFinal\"": "49\""
  },
  {
    "\"StudentID": "\"54733",
    "Surname": "Genizera",
    "GivenName": "John Lester",
    "MiddleInitial": "C.",
    "Q1": "",
    "Q2": "31",
    "Q3": "",
    "Midterm": "69",
    "Q4": "23",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "48",
    "Tentative Grade": "57",
    "Exempted": "No",
    "TargetFinal\"": "21\""
  },
  {
    "\"StudentID": "\"46205",
    "Surname": "Gilo",
    "GivenName": "Jan Armen",
    "MiddleInitial": "A.",
    "Q1": "0",
    "Q2": "14",
    "Q3": "",
    "Midterm": "34",
    "Q4": "3",
    "Q5": "4",
    "Q6": "34",
    "PreFinals": "18",
    "Tentative Grade": "26.75",
    "Exempted": "No",
    "TargetFinal\"": "81.5\""
  },
  {
    "\"StudentID": "\"56506",
    "Surname": "Granito",
    "GivenName": "Hen Ellysa",
    "MiddleInitial": "T.",
    "Q1": "2",
    "Q2": "20",
    "Q3": "",
    "Midterm": "33",
    "Q4": "3",
    "Q5": "9",
    "Q6": "34",
    "PreFinals": "21",
    "Tentative Grade": "30.5",
    "Exempted": "No",
    "TargetFinal\"": "74\""
  },
  {
    "\"StudentID": "\"54520",
    "Surname": "Leones",
    "GivenName": "Germaine Mae",
    "MiddleInitial": "C.",
    "Q1": "11",
    "Q2": "24",
    "Q3": "",
    "Midterm": "56",
    "Q4": "17",
    "Q5": "33",
    "Q6": "34",
    "PreFinals": "26",
    "Tentative Grade": "50.25",
    "Exempted": "No",
    "TargetFinal\"": "34.5\""
  },
  {
    "\"StudentID": "\"56091",
    "Surname": "Llave",
    "GivenName": "John paul",
    "MiddleInitial": "D.",
    "Q1": "5",
    "Q2": "5",
    "Q3": "",
    "Midterm": "33",
    "Q4": "24",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "22",
    "Tentative Grade": "36.5",
    "Exempted": "No",
    "TargetFinal\"": "62\""
  },
  {
    "\"StudentID": "\"50292",
    "Surname": "Matalubos",
    "GivenName": "Tommy",
    "MiddleInitial": "M.",
    "Q1": "6",
    "Q2": "8",
    "Q3": "",
    "Midterm": "28",
    "Q4": "17",
    "Q5": "12",
    "Q6": "34",
    "PreFinals": "16",
    "Tentative Grade": "30.25",
    "Exempted": "No",
    "TargetFinal\"": "74.5\""
  },
  {
    "\"StudentID": "\"54630",
    "Surname": "Mendoza",
    "GivenName": "Arabella ",
    "MiddleInitial": "A.",
    "Q1": "2",
    "Q2": "27",
    "Q3": "",
    "Midterm": "32",
    "Q4": "25",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "17",
    "Tentative Grade": "36.75",
    "Exempted": "No",
    "TargetFinal\"": "61.5\""
  },
  {
    "\"StudentID": "\"51534",
    "Surname": "Nitro",
    "GivenName": "Philip John",
    "MiddleInitial": "S.",
    "Q1": "3",
    "Q2": "10",
    "Q3": "",
    "Midterm": "29",
    "Q4": "10",
    "Q5": "2",
    "Q6": "",
    "PreFinals": "10",
    "Tentative Grade": "16",
    "Exempted": "No",
    "TargetFinal\"": "103\""
  },
  {
    "\"StudentID": "\"55594",
    "Surname": "Pagmanua",
    "GivenName": "Kerbie Kent",
    "MiddleInitial": "B.",
    "Q1": "9",
    "Q2": "27",
    "Q3": "",
    "Midterm": "46",
    "Q4": "21",
    "Q5": "27",
    "Q6": "34",
    "PreFinals": "28",
    "Tentative Grade": "48",
    "Exempted": "No",
    "TargetFinal\"": "39\""
  },
  {
    "\"StudentID": "\"55895",
    "Surname": "Pangilinan",
    "GivenName": "Fiona Ashley",
    "MiddleInitial": "L.",
    "Q1": "6",
    "Q2": "29",
    "Q3": "",
    "Midterm": "47",
    "Q4": "23",
    "Q5": "29",
    "Q6": "34",
    "PreFinals": "25",
    "Tentative Grade": "48.25",
    "Exempted": "No",
    "TargetFinal\"": "38.5\""
  },
  {
    "\"StudentID": "\"54398",
    "Surname": "Parcon",
    "GivenName": "Thed Joshua",
    "MiddleInitial": "T.",
    "Q1": "5",
    "Q2": "8",
    "Q3": "",
    "Midterm": "42",
    "Q4": "23",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "24",
    "Tentative Grade": "39.75",
    "Exempted": "No",
    "TargetFinal\"": "55.5\""
  },
  {
    "\"StudentID": "\"48158",
    "Surname": "Patrona",
    "GivenName": "Charles Adrian",
    "MiddleInitial": "C.",
    "Q1": "3",
    "Q2": "9",
    "Q3": "",
    "Midterm": "28",
    "Q4": "17",
    "Q5": "12",
    "Q6": "34",
    "PreFinals": "13",
    "Tentative Grade": "29",
    "Exempted": "No",
    "TargetFinal\"": "77\""
  },
  {
    "\"StudentID": "\"56584",
    "Surname": "Perez",
    "GivenName": "Leonardo",
    "MiddleInitial": "C.",
    "Q1": "29",
    "Q2": "23",
    "Q3": "",
    "Midterm": "59",
    "Q4": "24",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "38",
    "Tentative Grade": "57.5",
    "Exempted": "No",
    "TargetFinal\"": "20\""
  },
  {
    "\"StudentID": "\"49174",
    "Surname": "Polido",
    "GivenName": "Rio",
    "MiddleInitial": "P.",
    "Q1": "5",
    "Q2": "2",
    "Q3": "",
    "Midterm": "24",
    "Q4": "25",
    "Q5": "10",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "28.5",
    "Exempted": "No",
    "TargetFinal\"": "78\""
  },
  {
    "\"StudentID": "\"51521",
    "Surname": "Quasco",
    "GivenName": "Amy Rose",
    "MiddleInitial": "F.",
    "Q1": "8",
    "Q2": "8",
    "Q3": "",
    "Midterm": "27",
    "Q4": "13",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "8",
    "Tentative Grade": "30.25",
    "Exempted": "No",
    "TargetFinal\"": "74.5\""
  },
  {
    "\"StudentID": "\"54522",
    "Surname": "Querubin",
    "GivenName": "Alyzza Faith",
    "MiddleInitial": "A.",
    "Q1": "8",
    "Q2": "21",
    "Q3": "",
    "Midterm": "72",
    "Q4": "25",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "26",
    "Tentative Grade": "52.25",
    "Exempted": "No",
    "TargetFinal\"": "30.5\""
  },
  {
    "\"StudentID": "\"46601",
    "Surname": "Solis",
    "GivenName": "Rose Ann",
    "MiddleInitial": "S.",
    "Q1": "5",
    "Q2": "11",
    "Q3": "",
    "Midterm": "44",
    "Q4": "10",
    "Q5": "2",
    "Q6": "34",
    "PreFinals": "20",
    "Tentative Grade": "31.5",
    "Exempted": "No",
    "TargetFinal\"": "72\""
  },
  {
    "\"StudentID": "\"46904",
    "Surname": "Solis",
    "GivenName": "Zybells",
    "MiddleInitial": "L.",
    "Q1": "7",
    "Q2": "29",
    "Q3": "",
    "Midterm": "41",
    "Q4": "21",
    "Q5": "27",
    "Q6": "34",
    "PreFinals": "21",
    "Tentative Grade": "45",
    "Exempted": "No",
    "TargetFinal\"": "45\""
  },
  {
    "\"StudentID": "\"52456",
    "Surname": "Tabifranca ",
    "GivenName": "Tommy Jones",
    "MiddleInitial": "G.",
    "Q1": "4",
    "Q2": "4",
    "Q3": "",
    "Midterm": "45",
    "Q4": "3",
    "Q5": "9",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "28.25",
    "Exempted": "No",
    "TargetFinal\"": "78.5\""
  },
  {
    "\"StudentID": "\"51598",
    "Surname": "Tolentino",
    "GivenName": "Cathlyn Joy ",
    "MiddleInitial": "A.",
    "Q1": "6",
    "Q2": "6",
    "Q3": "",
    "Midterm": "47",
    "Q4": "17",
    "Q5": "33",
    "Q6": "34",
    "PreFinals": "18",
    "Tentative Grade": "40.25",
    "Exempted": "No",
    "TargetFinal\"": "54.5\""
  },
  {
    "\"StudentID": "\"56422",
    "Surname": "Torreña",
    "GivenName": "Harold",
    "MiddleInitial": "B.",
    "Q1": "7",
    "Q2": "13",
    "Q3": "",
    "Midterm": "51",
    "Q4": "21",
    "Q5": "14",
    "Q6": "",
    "PreFinals": "15",
    "Tentative Grade": "30.25",
    "Exempted": "No",
    "TargetFinal\"": "74.5\""
  },
  {
    "\"StudentID": "\"55173",
    "Surname": "VILLAR",
    "GivenName": "CRYSTHAL JOY",
    "MiddleInitial": "D.",
    "Q1": "7",
    "Q2": "19",
    "Q3": "",
    "Midterm": "36",
    "Q4": "23",
    "Q5": "29",
    "Q6": "34",
    "PreFinals": "18",
    "Tentative Grade": "41.5",
    "Exempted": "No",
    "TargetFinal\"": "52\""
  },
  {
    "\"StudentID": "\"50991",
    "Surname": "Villote ",
    "GivenName": "Julynio ",
    "MiddleInitial": "S.",
    "Q1": "0",
    "Q2": "14",
    "Q3": "",
    "Midterm": "34",
    "Q4": "3",
    "Q5": "4",
    "Q6": "34",
    "PreFinals": "25",
    "Tentative Grade": "28.5",
    "Exempted": "No",
    "TargetFinal\"": "78\""
  },
  {
    "\"StudentID": "\"56800",
    "Surname": "YMALAY",
    "GivenName": "JAMESON",
    "MiddleInitial": "C.",
    "Q1": "16",
    "Q2": "19",
    "Q3": "",
    "Midterm": "45",
    "Q4": "25",
    "Q5": "23",
    "Q6": "34",
    "PreFinals": "14",
    "Tentative Grade": "44",
    "Exempted": "No",
    "TargetFinal\"": "47\""
  }
];